=== GENIVI/navigation/api/poi-service/introspect.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wmh="http://www.wmhelp.com/2003/eGenerator" elementFormDefault="qualified">
  <!--     xmlns="introspect.dtd"
	targetNamespace="introspect.dtd"> -->
  <xs:element name="node">
    <xs:annotation>
      <xs:documentation> DTD for D-Bus Introspection data
			</xs:documentation>
      <xs:documentation> (C) 2005-02-02 David A. Wheeler; released under
				the D-Bus licenses,
				GNU GPL version 2 (or greater) and AFL 1.1 (or
				greater)
			</xs:documentation>
      <xs:documentation> see D-Bus specification for documentation
			</xs:documentation>
      <xs:documentation> Method arguments SHOULD include "direction",
				while
				signal and error arguments SHOULD not (since there's no point).
				The
				DTD format can't express that subtlety.
			</xs:documentation>
      <xs:documentation> Generic metadata </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="node"/>
        <xs:element name="interface" type="interfaceType"/>
      </xs:choice>
      <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="interfaceType">
    <xs:sequence>
      <xs:element name="version" type="xs:string"/>
      <xs:element name="doc" type="docType"/>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="method" type="methodType"/>
        <xs:element name="signal" type="signalType"/>
        <xs:element name="property" type="propertyType"/>
        <xs:element name="annotation" type="annotationType"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:complexType name="methodType">
    <xs:sequence>
      <xs:element name="status" type="statusType" minOccurs="0"/>
      <xs:element name="poc" type="pocType" minOccurs="0"/>
      <xs:element name="obligation" type="obligationType" minOccurs="0"/>
      <xs:element name="doc" type="docType"/>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="arg" type="argType"/>
        <xs:element name="annotation" type="annotationType"/>
        <xs:element name="error" type="errorType"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:complexType name="signalType">
    <xs:sequence>
      <xs:element name="status" type="statusType" minOccurs="0"/>
      <xs:element name="poc" type="pocType" minOccurs="0"/>
      <xs:element name="obligation" type="obligationType" minOccurs="0"/>
      <xs:element name="doc" type="docType"/>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="arg" type="argType"/>
        <xs:element name="annotation" type="annotationType"/>
        <xs:element name="error" type="errorType"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:complexType name="argType">
    <xs:sequence>
      <xs:element name="doc" type="docType"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="type" type="xs:string" use="required"/>
    <xs:attribute name="direction" default="in">
      <xs:simpleType>
        <xs:restriction base="xs:NMTOKEN">
          <xs:enumeration value="in"/>
          <xs:enumeration value="out"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="propertyType">
    <xs:annotation>
      <xs:documentation> AKA "attribute" </xs:documentation>
    </xs:annotation>
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="status" type="statusType" minOccurs="0"/>
      <xs:element name="poc" type="pocType" minOccurs="0"/>
      <xs:element name="obligation" type="obligationType" minOccurs="0"/>
      <xs:element name="annotation" type="annotationType"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="type" type="xs:string" use="required"/>
    <xs:attribute name="access" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:NMTOKEN">
          <xs:enumeration value="read"/>
          <xs:enumeration value="write"/>
          <xs:enumeration value="readwrite"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="annotationType">
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:string" use="required"/>
  </xs:complexType>
  <!-- proprietary extensions from LBS-EG -->
  <!--  	<xs:complexType name="versionType" /> -->
  <xs:complexType name="docType">
    <xs:sequence>
      <!--  			<xs:element maxOccurs="unbounded" name="line" type="lineType"/> -->
      <xs:element maxOccurs="unbounded" name="line" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="statusType">
    <xs:restriction base="xs:NMTOKEN">
      <xs:enumeration value="Approved"/>
      <xs:enumeration value="Pending"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="pocType">
    <xs:restriction base="xs:NMTOKEN">
      <xs:enumeration value="Yes"/>
      <xs:enumeration value="No"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="obligationType">
    <xs:restriction base="xs:NMTOKEN">
      <xs:enumeration value="Mandatory"/>
      <xs:enumeration value="Optional"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="errorType">
    <xs:sequence>
      <xs:element name="doc" type="docType"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>
  <!--  	<xs:complexType name="lineType" /> -->
</xs:schema>

=== GENIVI/navigation/api/map-viewer/genivi-mapviewer-configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="introspect.xsl"?>
<!-- SPDX-License-Identifier: MPL-2.0
     Copyright (C) 2014, BMW Car IT GmbH, Continental Automotive GmbH, PCA Peugeot Citroën, XS Embedded GmbH,   TomTom International B.V., Alpine Electronics R&D Europe GmbH, AISIN AW CO., LTD.,  Neusoft Technology Solutions GmbH, Jaguar Land Rover Limited, Visteon Corporation
     This Source Code Form is subject to the terms of the
     Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed with
     this file, you can obtain one at http://mozilla.org/MPL/2.0/.
-->
<node xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="/org/genivi/mapviewer" xsi:noNamespaceSchemaLocation="introspect.xsd">
  <interface name="org.genivi.mapviewer.Configuration">
    <version>3.0.0 (21-01-2014)</version>
    <doc>
      <line>Configuration = This interface offers functions to set and retrieve configuration parameters</line>
    </doc>
    <method name="GetVersion">
      <doc>
        <line>GetVersion = This method returns the API version implemented by the server application</line>
      </doc>
      <arg name="version" type="(qqqs)" direction="out">
        <doc>
          <line>version = struct(major,minor,micro,date)</line>
          <line>major = when the major changes, then backward compatibility with previous releases is not granted</line>
          <line>minor = when the minor changes, then backward compatibility with previous releases is granted, but something changed in the implementation of the API (e.g. new methods may have been added)</line>
          <line>micro = when the micro changes, then backward compatibility with previous releases is granted (bug fixes or documentation modifications)</line>
          <line>date = release date (e.g. 21-06-2011)</line>
        </doc>
      </arg>
    </method>
    <method name="SetUnitsOfMeasurement">
      <doc>
        <line>SetUnitsOfMeasurement = This method sets the units of measurement</line>
      </doc>
      <arg name="unitsOfMeasurementList" type="a{ii}" direction="in">
        <doc>
          <line>unitsOfMeasurementList = array[unitsOfMeasurement]</line>
          <line>unitsOfMeasurement = tuple (key,value)</line>
          <line>key = enum(INVALID,LENGTH, ... )</line>
          <line>key = LENGTH, value = value of type 'i', that represents an enum(INVALID,METER,MILE, ... )</line>
        </doc>
      </arg>
    </method>
    <method name="GetUnitsOfMeasurement">
      <doc>
        <line>GetUnitsOfMeasurement = This method retrieves the units of measurement</line>
      </doc>
      <arg name="unitsOfMeasurementList" type="a{ii}" direction="out">
        <doc>
          <line>unitsOfMeasurementList = array[unitsOfMeasurement]</line>
          <line>unitsOfMeasurement = tuple (key,value)</line>
          <line>key = enum(INVALID,LENGTH, ... )</line>
          <line>key = LENGTH, value = value of type 'i', that represents an enum(INVALID,METER,MILE, ... )</line>
        </doc>
      </arg>
    </method>
    <method name="GetSupportedUnitsOfMeasurement">
      <doc>
        <line>GetSupportedUnitsOfMeasurement = This method retrieves the supported units of measurement</line>
      </doc>
      <arg name="unitsOfMeasurementList" type="a{iai}" direction="out">
        <doc>
          <line>unitsOfMeasurementList = array[unitsOfMeasurement]</line>
          <line>unitsOfMeasurement = dictionary[key,value]</line>
          <line>dictionary = array of tuples (key,value)</line>
          <line>key = enum(INVALID,LENGTH, ... )</line>
          <line>key = LENGTH, value = value of type 'ai'; 'i' is an enum(INVALID,METER,MILE, ... )</line>
        </doc>
      </arg>
    </method>
    <method name="SetTimeFormat">
      <doc>
        <line>SetTimeFormat = This method sets the time format</line>
      </doc>
      <arg name="timeFormat" type="i" direction="in">
        <doc>
          <line>timeFormat = enum(INVALID,12H,24H, ... )</line>
        </doc>
      </arg>
    </method>
    <method name="GetTimeFormat">
      <doc>
        <line>GetTimeFormat = This method retrieves the time format</line>
      </doc>
      <arg name="timeFormat" type="i" direction="out">
        <doc>
          <line>timeFormat = enum(INVALID,12H,24H, ... )</line>
        </doc>
      </arg>
    </method>
    <method name="GetSupportedTimeFormats">
      <doc>
        <line>GetSupportedTimeFormats = This method retrieves the supported time formats</line>
      </doc>
      <arg name="timeFormatList" type="ai" direction="out">
        <doc>
          <line>timeFormatList = array[timeFormat]</line>
          <line>timeFormat = enum(INVALID,12H,24H, ... )</line>
        </doc>
      </arg>
    </method>
    <method name="SetCoordinatesFormat">
      <doc>
        <line>SetCoordinatesFormat = This method sets the coordinates format</line>
      </doc>
      <arg name="coordinatesFormat" type="i" direction="in">
        <doc>
          <line>coordinatesFormat = enum(INVALID,DEGREES,MINUTES,SECONDS, ... )</line>
          <line>DEGREES format = d.dº</line>
          <line>MINUTES format = dºm.m'</line>
          <line>SECONDS format = dºm's"</line>
        </doc>
      </arg>
    </method>
    <method name="GetCoordinatesFormat">
      <doc>
        <line>GetCoordinatesFormat = This method retrieves the coordinates format</line>
      </doc>
      <arg name="coordinatesFormat" type="i" direction="out">
        <doc>
          <line>coordinatesFormat = enum(INVALID,DEGREES,MINUTES,SECONDS, ... )</line>
          <line>DEGREES format = d.dº</line>
          <line>MINUTES format = dºm.m'</line>
          <line>SECONDS format = dºm's"</line>
        </doc>
      </arg>
    </method>
    <method name="GetSupportedCoordinatesFormats">
      <doc>
        <line>GetSupportedCoordinatesFormats = This method retrieves the supported coordinates formats</line>
      </doc>
      <arg name="coordinatesFormatList" type="ai" direction="out">
        <doc>
          <line>coordinatesFormatList = array[coordinatesFormat]</line>
          <line>coordinatesFormat = enum(INVALID,DEGREES,MINUTES,SECONDS, ... )</line>
          <line>DEGREES format = d.dº</line>
          <line>MINUTES format = dºm.m'</line>
          <line>SECONDS format = dºm's"</line>
        </doc>
      </arg>
    </method>
    <method name="SetLocale">
      <doc>
        <line>SetLocale = This method sets the current language and country</line>
      </doc>
      <arg name="languageCode" type="s" direction="in">
        <doc>
          <line>languageCode = ISO 639‐3 language code (lower case)</line>
        </doc>
      </arg>
      <arg name="countryCode" type="s" direction="in">
        <doc>
          <line>countryCode = ISO 3166‐1 alpha 3 country code (upper case)</line>
        </doc>
      </arg>
      <arg name="scriptCode" type="s" direction="in">
        <doc>
          <line>scriptCode= ISO 15924 alpha 4 script code (upper case)</line>
        </doc>
      </arg>
    </method>
    <method name="GetLocale">
      <doc>
        <line>GetLocale = This method retrieves the current language and country</line>
      </doc>
      <arg name="languageCode" type="s" direction="out">
        <doc>
          <line>languageCode = ISO 639‐3 language code (lower case)</line>
        </doc>
      </arg>
      <arg name="countryCode" type="s" direction="out">
        <doc>
          <line>countryCode = ISO 3166‐1 alpha 3 country code (upper case)</line>
        </doc>
      </arg>
      <arg name="scriptCode" type="s" direction="out">
        <doc>
          <line>scriptCode= ISO 15924 alpha 4 script code (upper case)</line>
        </doc>
      </arg>
    </method>
    <method name="GetSupportedLocales">
      <doc>
        <line>GetSupportedLocales = This method retrieves the supported languages and countries</line>
      </doc>
      <arg name="localeList" type="a(sss)" direction="out">
        <doc>
          <line>localeList = array[struct(languageCode,countryCode)]</line>
          <line>languageCode = ISO 639-3 language code (lower case)</line>
          <line>countryCode = ISO 3166-1 alpha 3 country code (upper case)</line>
          <line>scriptCode = ISO 15924 alpha 4 script code (upper case)</line>
        </doc>
      </arg>
    </method>
    <signal name="ConfigurationChanged">
      <doc>
        <line>ConfigurationChanged = This signal is sent to the clients when one or more configuration settings changes</line>
      </doc>
      <arg name="changedSettings" type="ai">
        <doc>
          <line>changedSettings = array[setting]</line>
          <line>setting = enum(INVALID,UNITS_OF_MEASUREMENT,LOCALE,TIME_FORMAT,COORDINATES_FORMAT, ... )</line>
        </doc>
      </arg>
    </signal>
  </interface>
</node>

=== GENIVI/navigation/api/speech-service/genivi-speechservice-speechoutput.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="introspect.xsl"?>
<!-- This D-Bus Introspection model has been created from a Franca IDL file. -->
<!-- Input file: 'SpeechOutput.fidl' -->
<node xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="introspect.xsd" name="org.genivi.hmi.speechservice">
  <interface name="org.genivi.hmi.speechservice.SpeechOutput">
    <version>0.1</version>
    <method name="getVersion">
      <doc>
        <line>getVersion = This method returns the API version implemented by the content access module.</line>
      </doc>
      <arg direction="out" name="version" type="(qqqs)">
        <doc>
          <line>version (of type Version) = .</line>
          <line>Version struct[versionMajor, versionMinor, versionMicro, date] = version.</line>
          <line>0: Version.versionMajor ('q') = when the major changes, then backward compatibility with previous releases is not granted.</line>
          <line>1: Version.versionMinor ('q') = when the minor changes, then backward compatibility with previous releases is granted, but something changed in the implementation of the API (e.g. new methods may have been added).</line>
          <line>2: Version.versionMicro ('q') = when the micro changes, then backward compatibility with previous releases is granted (bug fixes or documentation modifications).</line>
          <line>3: Version.date ('s') = release date (e.g. 21-06-2011).</line>
        </doc>
      </arg>
    </method>
    <method name="openPrompter">
      <doc>
        <line>openPrompter = Must be called to open a SpeechOutputService session and to get the audio connection.</line>
      </doc>
      <arg direction="in" name="connectionType" type="u">
        <doc>
          <line>connectionType (of type ConnectionType) = Sets the Audio connection that should be used for the prompter application.</line>
          <line>enum[CT_NAVIGATION (null), CT_READER (null), CT_GEN_HIGH (null), CT_GEN_MEDIUM (null), CT_GEN_LOW (null), CT_MAX (null)]</line>
        </doc>
      </arg>
      <arg direction="in" name="preProcessingType" type="u">
        <doc>
          <line>preProcessingType (of type PreProcessingType) = Sets the text normaization mode and which active prompt data base will be activated.</line>
          <line>enum[PPT_DIALOG (null), PPT_NAVIGATION (null), PPT_NONE (null), PPT_READER (null), PPT_MAX (null)]</line>
        </doc>
      </arg>
    </method>
    <method name="addTextChunk">
      <doc>
        <line>addTextChunk = The prompter must be opened to trigger the playback of the provided prompt.</line>
        <line>The prompt length must not exceed the length of a PromptChunk buffer.</line>
        <line>Synthesizes the provided text or if using the escape sequence of the engine supplier a wave file in a supported sampling rate is provided, the system will back back also wave files.</line>
        <line>The text will be normalized using the context identifier provided to openprompter. This applies to matching prerecorded files as well as the synthesis of number and words that are matched to a lexical dictionary.</line>
        <line>The synthesize will start if the prompter is idle, if the prompter is already playing the playback will be delayed until all previously added text chunks are played back. For every text chunk provided a notification will be send.</line>
      </doc>
      <arg direction="in" name="chunk" type="s">
        <doc>
          <line>chunk (of type Chunk) = String containing the prompt to play.</line>
          <line>lineComment to be defined</line>
        </doc>
      </arg>
      <arg direction="out" name="chunkID" type="u">
        <doc>
          <line>chunkID (of type ChunkID) = Index of the added prompt, zero based.</line>
          <line>lineComment to be defined</line>
        </doc>
      </arg>
    </method>
    <method name="abortPrompter">
      <doc>
        <line>abortPrompter = A prompt must be playing to perform an abort action. If no prompting operation in progress there will be no reaction of the system.</line>
      </doc>
    </method>
    <method name="closePrompter">
      <doc>
        <line>closePrompter = The prompter is closed after the last text chunk submitted has finished playing.</line>
      </doc>
    </method>
    <signal name="notifyConnectionStatus">
      <doc>
        <line>notifyConnectionStatus = Notifies the connection status</line>
      </doc>
      <arg direction="out" name="connectionStatus" type="u">
        <doc>
          <line>connectionStatus (of type ConnectionStatus) = Client connection status.</line>
          <line>enum[CS_UNKNOWN (null), CS_ESTABLISHED (null), CS_REFUSED (null), CS_POSSIBLE (null), CS_PENDING (null), CS_PAUSED (null), CS_TERMINATED (null), CS_MAX (null)]</line>
        </doc>
      </arg>
    </signal>
    <signal name="notifyMarkerReached">
      <doc>
        <line>notifyMarkerReached = Notifies the last reached marker.</line>
      </doc>
      <arg direction="out" name="chunkID" type="u">
        <doc>
          <line>chunkID (of type ChunkID) = ID of the processed chunk.</line>
          <line>lineComment to be defined</line>
        </doc>
      </arg>
      <arg direction="out" name="marker" type="s">
        <doc>
          <line>marker (of type Marker) = String with the name of the reached marker (if TTS engine supports inserting bookmarks with a name).</line>
          <line>lineComment to be defined</line>
        </doc>
      </arg>
    </signal>
    <signal name="notifyQueueStatus">
      <doc>
        <line>notifyQueueStatus = Notifies the queue status.</line>
      </doc>
      <arg direction="out" name="queueStatus" type="u">
        <doc>
          <line>queueStatus (of type QueueStatus) = Fill status of the text buffer.</line>
          <line>enum[QS_UNKNOWN (null), QS_FULL (null), QS_HIGH_FILL (null), QS_LOW_FILL (null), QS_MAX (null)]</line>
        </doc>
      </arg>
    </signal>
    <signal name="notifyTTSStatus">
      <doc>
        <line>notifyTTSStatus = Notifies the TTS engine status.</line>
      </doc>
      <arg direction="out" name="ttsStatus" type="u">
        <doc>
          <line>ttsStatus (of type TtsStatus) = Current status of the TTS.</line>
          <line>enum[TS_UNKNOWN (null), TS_NOT_INITIALIZED (null), TS_ACTIVE (null), TS_ABORTED (null), TS_MARKER (null), TS_IDLE (null), TS_ENQUEUED (null), TS_FINISHED (null), TS_FAILED (null), TS_MAX (null)]</line>
        </doc>
      </arg>
    </signal>
  </interface>
</node>

=== GENIVI/navigation/api/navigation-core/genivi-navigationcore-session.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="introspect.xsl"?>
<node xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="/org/genivi/navigationcore" xsi:noNamespaceSchemaLocation="introspect.xsd">
  <interface name="org.genivi.navigationcore.Session">
    <version>3.0.0 (22-01-2014)</version>
    <doc>
      <line>Session = This interface offers functions to create and delete sessions</line>
    </doc>
    <method name="GetVersion">
      <doc>
        <line>GetVersion = This method returns the API version implemented by the server application</line>
      </doc>
      <arg name="version" type="(qqqs)" direction="out">
        <doc>
          <line>version = struct(major,minor,micro,date)</line>
          <line>major = when the major changes, then backward compatibility with previous releases is not granted</line>
          <line>minor = when the minor changes, then backward compatibility with previous releases is granted, but something changed in the implementation of the API (e.g. new methods may have been added)</line>
          <line>micro = when the micro changes, then backward compatibility with previous releases is granted (bug fixes or documentation modifications)</line>
          <line>date = release date (e.g. 21-06-2011)</line>
        </doc>
      </arg>
    </method>
    <method name="CreateSession">
      <doc>
        <line>CreateSession = This method creates a new session</line>
      </doc>
      <arg name="client" type="s" direction="in">
        <doc>
          <line>client = name or identifier of the client application that requests a new session</line>
          <line>The navigation core must internally associate this name to the returned session handle</line>
          <line>This parameter can be used to identify the client application and determine if a given feature is enabled for it</line>
        </doc>
      </arg>
      <arg name="sessionHandle" type="u" direction="out">
        <doc>
          <line>sessionHandle = Session handle. Range[0x0:0x7fffffff]. 0x0 is reserved as an invalid handle value</line>
        </doc>
      </arg>
      <error name="org.genivi.navigationcore.Session.Error.NoMoreSessionHandles">
        <doc>
          <line>This error is generated if no more session handles are available</line>
        </doc>
      </error>
    </method>
    <method name="DeleteSession">
      <doc>
        <line>DeleteSession = This method deletes a session and its associated resources</line>
      </doc>
      <arg name="sessionHandle" type="u" direction="in">
        <doc>
          <line>sessionHandle = Session handle. Range[0x0:0x7fffffff]. 0x0 is reserved as an invalid handle value</line>
        </doc>
      </arg>
      <error name="org.genivi.navigationcore.Session.Error.SessionNotAvailable">
        <doc>
          <line>This error is generated if an application tries to delete a session handle that is not available</line>
        </doc>
      </error>
    </method>
    <method name="GetSessionStatus">
      <doc>
        <line>GetSessionStatus = This method returns whether a given session handle is available or not (for example because it was deleted)</line>
      </doc>
      <arg name="sessionHandle" type="u" direction="in">
        <doc>
          <line>sessionHandle = Session handle. Range[0x0:0x7fffffff]. 0x0 is reserved as an invalid handle value</line>
        </doc>
      </arg>
      <arg name="sessionStatus" type="q" direction="out">
        <doc>
          <line>sessionStatus = enum(INVALID,AVAILABLE,NOT_AVAILABLE)</line>
        </doc>
      </arg>
    </method>
    <method name="GetAllSessions">
      <doc>
        <line>GetAllSessions = This method returns a list of all available sessions</line>
      </doc>
      <arg name="sessionsList" type="a(us)" direction="out">
        <doc>
          <line>sessionsList = array[struct(sessionHandle,client)]</line>
          <line>sessionHandle = Session handle. Range[0x0:0x7fffffff]. 0x0 is reserved as an invalid handle value</line>
          <line>client = name or identifier of the client application that requested the sessionHandle</line>
        </doc>
      </arg>
    </method>
    <signal name="SessionDeleted">
      <doc>
        <line>SessionDeleted = This signal is emitted when a session is deleted</line>
      </doc>
      <arg name="sessionHandle" type="u">
        <doc>
          <line>sessionHandle = Session handle. Range[0x0:0x7fffffff]. 0x0 is reserved as an invalid handle value</line>
        </doc>
      </arg>
    </signal>
  </interface>
</node>
